import BetterStorage from "../src";
const storage = new BetterStorage('token')
storage.set("ijj4544JHaJhbGciOiJIUzUxMiIsImlhdCI6MTYyMzUxMjE1MCwiZXhwIjoxNjI2MTA0MTUwfQ.eyJ1aWQiOjIsInR5cGUiOjEwMCwic2NvcGUiOiJVc2VyU2NvcGUifQ.Bnt3NVx-NkmWulzxozQTxnHXMqeTliDb7kzN_kA8Zqpx3BqSd-i82VfIwfrqLR5C6bZlwsNewAA38jRqIIdn8g")
storage.set('name', 'dengguochao')
storage.set('age', '1121212')
// console.log(storage.get('name'))
// storage.clear()
// storage.set('name', 'china')
console.log(storage.getAll())
// console.log(storage.clear())
